@startuml overview

title DotBPE主要调用流程
legend
    DotBPE主要调用流程
end legend



autonumber

IInvokeCaller -> IRpcClient : AsyncCall(Message)
IRpcClient -> IServiceRouter : GetServiceRouter(Message)
IRpcClient <-- IServiceRouter : IRouter

alt IRouter.RouterMode == "Remote"
    IRpcClient -> IRpcClient : SendAsync(EndPoint,Message)
else IRouter.RouterMode == "Local"
    IRpcClient -> IServiceActorLocator : GetServiceActor(Message)
    IRpcClient <-- IServiceActorLocator : IServiceActor
    IRpcClient -> IServiceActor : ReceiveAsync(ISocketContext,Message)
end

@enduml

