// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dotbpe_option.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DotBPE.ProtoBuf {

  /// <summary>Holder for reflection information generated from dotbpe_option.proto</summary>
  public static partial class DotbpeOptionReflection {

    #region Descriptor
    /// <summary>File descriptor for dotbpe_option.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DotbpeOptionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNkb3RicGVfb3B0aW9uLnByb3RvEgZkb3RicGUaIGdvb2dsZS9wcm90b2J1",
            "Zi9kZXNjcmlwdG9yLnByb3RvOjUKCnNlcnZpY2VfaWQSHy5nb29nbGUucHJv",
            "dG9idWYuU2VydmljZU9wdGlvbnMYuY4DIAEoBTpJCh5kaXNhYmxlX2dlbmVy",
            "aWNfc2VydmljZV9jbGllbnQSHy5nb29nbGUucHJvdG9idWYuU2VydmljZU9w",
            "dGlvbnMYu44DIAEoCDpJCh5kaXNhYmxlX2dlbmVyaWNfc2VydmljZV9zZXJ2",
            "ZXISHy5nb29nbGUucHJvdG9idWYuU2VydmljZU9wdGlvbnMYvI4DIAEoCDo0",
            "CgptZXNzYWdlX2lkEh4uZ29vZ2xlLnByb3RvYnVmLk1ldGhvZE9wdGlvbnMY",
            "uo4DIAEoBTpHCh9kaXNhYmxlX2dlbmVyaWNfc2VydmljZXNfY2xpZW50Ehwu",
            "Z29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGLuOAyABKAg6RwofZGlzYWJs",
            "ZV9nZW5lcmljX3NlcnZpY2VzX3NlcnZlchIcLmdvb2dsZS5wcm90b2J1Zi5G",
            "aWxlT3B0aW9ucxi8jgMgASgIOjwKFGdlbmVyaWNfbWFya2Rvd25fZG9jEhwu",
            "Z29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGL2OAyABKAhCEqoCD0RvdEJQ",
            "RS5Qcm90b0J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
