// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dotbpe_option.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HelloRpc.Common {

  /// <summary>Holder for reflection information generated from dotbpe_option.proto</summary>
  public static partial class DotbpeOptionReflection {

    #region Descriptor
    /// <summary>File descriptor for dotbpe_option.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DotbpeOptionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNkb3RicGVfb3B0aW9uLnByb3RvEgZkb3RicGUaIGdvb2dsZS9wcm90b2J1",
            "Zi9kZXNjcmlwdG9yLnByb3RvOjQKCnNlcnZpY2VfaWQSHy5nb29nbGUucHJv",
            "dG9idWYuU2VydmljZU9wdGlvbnMYkE4gASgFOjMKCm1lc3NhZ2VfaWQSHi5n",
            "b29nbGUucHJvdG9idWYuTWV0aG9kT3B0aW9ucxiQTiABKAVCEqoCD0hlbGxv",
            "UnBjLkNvbW1vbmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
