// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/plugin.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Compiler
{

    /// <summary>Holder for reflection information generated from compiler/plugin.proto</summary>
    public static partial class PluginReflection
    {

        #region Descriptor
        /// <summary>File descriptor for compiler/plugin.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static PluginReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "ChVjb21waWxlci9wbHVnaW4ucHJvdG8SGGdvb2dsZS5wcm90b2J1Zi5jb21w",
                  "aWxlchogZ29vZ2xlL3Byb3RvYnVmL2Rlc2NyaXB0b3IucHJvdG8ifQoUQ29k",
                  "ZUdlbmVyYXRvclJlcXVlc3QSGAoQZmlsZV90b19nZW5lcmF0ZRgBIAMoCRIR",
                  "CglwYXJhbWV0ZXIYAiABKAkSOAoKcHJvdG9fZmlsZRgPIAMoCzIkLmdvb2ds",
                  "ZS5wcm90b2J1Zi5GaWxlRGVzY3JpcHRvclByb3RvIqoBChVDb2RlR2VuZXJh",
                  "dG9yUmVzcG9uc2USDQoFZXJyb3IYASABKAkSQgoEZmlsZRgPIAMoCzI0Lmdv",
                  "b2dsZS5wcm90b2J1Zi5jb21waWxlci5Db2RlR2VuZXJhdG9yUmVzcG9uc2Uu",
                  "RmlsZRo+CgRGaWxlEgwKBG5hbWUYASABKAkSFwoPaW5zZXJ0aW9uX3BvaW50",
                  "GAIgASgJEg8KB2NvbnRlbnQYDyABKAlCUgocY29tLmdvb2dsZS5wcm90b2J1",
                  "Zi5jb21waWxlckIMUGx1Z2luUHJvdG9zWglwbHVnaW5fZ2+qAhhHb29nbGUu",
                  "UHJvdG9idWYuQ29tcGlsZXJiBnByb3RvMw=="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
                new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Compiler.CodeGeneratorRequest), global::Google.Protobuf.Compiler.CodeGeneratorRequest.Parser, new[]{ "FileToGenerate", "Parameter", "ProtoFile" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Compiler.CodeGeneratorResponse), global::Google.Protobuf.Compiler.CodeGeneratorResponse.Parser, new[]{ "Error", "File" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Compiler.CodeGeneratorResponse.Types.File), global::Google.Protobuf.Compiler.CodeGeneratorResponse.Types.File.Parser, new[]{ "Name", "InsertionPoint", "Content" }, null, null, null)})
                }));
        }
        #endregion

    }
    #region Messages
    /// <summary>
    ///  An encoded CodeGeneratorRequest is written to the plugin's stdin.
    /// </summary>
    public sealed partial class CodeGeneratorRequest : pb::IMessage<CodeGeneratorRequest>
    {
        private static readonly pb::MessageParser<CodeGeneratorRequest> _parser = new pb::MessageParser<CodeGeneratorRequest>(() => new CodeGeneratorRequest());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<CodeGeneratorRequest> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Google.Protobuf.Compiler.PluginReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CodeGeneratorRequest()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CodeGeneratorRequest(CodeGeneratorRequest other) : this()
        {
            fileToGenerate_ = other.fileToGenerate_.Clone();
            parameter_ = other.parameter_;
            protoFile_ = other.protoFile_.Clone();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CodeGeneratorRequest Clone()
        {
            return new CodeGeneratorRequest(this);
        }

        /// <summary>Field number for the "file_to_generate" field.</summary>
        public const int FileToGenerateFieldNumber = 1;
        private static readonly pb::FieldCodec<string> _repeated_fileToGenerate_codec
            = pb::FieldCodec.ForString(10);
        private readonly pbc::RepeatedField<string> fileToGenerate_ = new pbc::RepeatedField<string>();
        /// <summary>
        ///  The .proto files that were explicitly listed on the command-line.  The
        ///  code generator should generate code only for these files.  Each file's
        ///  descriptor will be included in proto_file, below.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<string> FileToGenerate
        {
            get { return fileToGenerate_; }
        }

        /// <summary>Field number for the "parameter" field.</summary>
        public const int ParameterFieldNumber = 2;
        private string parameter_ = "";
        /// <summary>
        ///  The generator parameter passed on the command-line.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Parameter
        {
            get { return parameter_; }
            set
            {
                parameter_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "proto_file" field.</summary>
        public const int ProtoFileFieldNumber = 15;
        private static readonly pb::FieldCodec<global::Google.Protobuf.Reflection.FileDescriptorProto> _repeated_protoFile_codec
            = pb::FieldCodec.ForMessage(122, global::Google.Protobuf.Reflection.FileDescriptorProto.Parser);
        private readonly pbc::RepeatedField<global::Google.Protobuf.Reflection.FileDescriptorProto> protoFile_ = new pbc::RepeatedField<global::Google.Protobuf.Reflection.FileDescriptorProto>();
        /// <summary>
        ///  FileDescriptorProtos for all files in files_to_generate and everything
        ///  they import.  The files will appear in topological order, so each file
        ///  appears before any file that imports it.
        ///
        ///  protoc guarantees that all proto_files will be written after
        ///  the fields above, even though this is not technically guaranteed by the
        ///  protobuf wire format.  This theoretically could allow a plugin to stream
        ///  in the FileDescriptorProtos and handle them one by one rather than read
        ///  the entire set into memory at once.  However, as of this writing, this
        ///  is not similarly optimized on protoc's end -- it will store all fields in
        ///  memory at once before sending them to the plugin.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        internal pbc::RepeatedField<global::Google.Protobuf.Reflection.FileDescriptorProto> ProtoFile
        {
            get { return protoFile_; }
        }


        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as CodeGeneratorRequest);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(CodeGeneratorRequest other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!fileToGenerate_.Equals(other.fileToGenerate_)) return false;
            if (Parameter != other.Parameter) return false;
            if (!protoFile_.Equals(other.protoFile_)) return false;
            return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            hash ^= fileToGenerate_.GetHashCode();
            if (Parameter.Length != 0) hash ^= Parameter.GetHashCode();
            hash ^= protoFile_.GetHashCode();
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            fileToGenerate_.WriteTo(output, _repeated_fileToGenerate_codec);
            if (Parameter.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(Parameter);
            }
            protoFile_.WriteTo(output, _repeated_protoFile_codec);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            size += fileToGenerate_.CalculateSize(_repeated_fileToGenerate_codec);
            if (Parameter.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Parameter);
            }
            size += protoFile_.CalculateSize(_repeated_protoFile_codec);
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(CodeGeneratorRequest other)
        {
            if (other == null)
            {
                return;
            }
            fileToGenerate_.Add(other.fileToGenerate_);
            if (other.Parameter.Length != 0)
            {
                Parameter = other.Parameter;
            }
            protoFile_.Add(other.protoFile_);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        input.SkipLastField();
                        break;
                    case 10:
                        {
                            fileToGenerate_.AddEntriesFrom(input, _repeated_fileToGenerate_codec);
                            break;
                        }
                    case 18:
                        {
                            Parameter = input.ReadString();
                            break;
                        }
                    case 122:
                        {
                            protoFile_.AddEntriesFrom(input, _repeated_protoFile_codec);
                            break;
                        }
                }
            }
        }

    }

    /// <summary>
    ///  The plugin writes an encoded CodeGeneratorResponse to stdout.
    /// </summary>
    public sealed partial class CodeGeneratorResponse : pb::IMessage<CodeGeneratorResponse>
    {
        private static readonly pb::MessageParser<CodeGeneratorResponse> _parser = new pb::MessageParser<CodeGeneratorResponse>(() => new CodeGeneratorResponse());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<CodeGeneratorResponse> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Google.Protobuf.Compiler.PluginReflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CodeGeneratorResponse()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CodeGeneratorResponse(CodeGeneratorResponse other) : this()
        {
            error_ = other.error_;
            file_ = other.file_.Clone();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CodeGeneratorResponse Clone()
        {
            return new CodeGeneratorResponse(this);
        }

        /// <summary>Field number for the "error" field.</summary>
        public const int ErrorFieldNumber = 1;
        private string error_ = "";
        /// <summary>
        ///  Error message.  If non-empty, code generation failed.  The plugin process
        ///  should exit with status code zero even if it reports an error in this way.
        ///
        ///  This should be used to indicate errors in .proto files which prevent the
        ///  code generator from generating correct code.  Errors which indicate a
        ///  problem in protoc itself -- such as the input CodeGeneratorRequest being
        ///  unparseable -- should be reported by writing a message to stderr and
        ///  exiting with a non-zero status code.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Error
        {
            get { return error_; }
            set
            {
                error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "file" field.</summary>
        public const int FileFieldNumber = 15;
        private static readonly pb::FieldCodec<global::Google.Protobuf.Compiler.CodeGeneratorResponse.Types.File> _repeated_file_codec
            = pb::FieldCodec.ForMessage(122, global::Google.Protobuf.Compiler.CodeGeneratorResponse.Types.File.Parser);
        private readonly pbc::RepeatedField<global::Google.Protobuf.Compiler.CodeGeneratorResponse.Types.File> file_ = new pbc::RepeatedField<global::Google.Protobuf.Compiler.CodeGeneratorResponse.Types.File>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::Google.Protobuf.Compiler.CodeGeneratorResponse.Types.File> File
        {
            get { return file_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as CodeGeneratorResponse);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(CodeGeneratorResponse other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Error != other.Error) return false;
            if (!file_.Equals(other.file_)) return false;
            return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Error.Length != 0) hash ^= Error.GetHashCode();
            hash ^= file_.GetHashCode();
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            if (Error.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(Error);
            }
            file_.WriteTo(output, _repeated_file_codec);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (Error.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
            }
            size += file_.CalculateSize(_repeated_file_codec);
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(CodeGeneratorResponse other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Error.Length != 0)
            {
                Error = other.Error;
            }
            file_.Add(other.file_);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        input.SkipLastField();
                        break;
                    case 10:
                        {
                            Error = input.ReadString();
                            break;
                        }
                    case 122:
                        {
                            file_.AddEntriesFrom(input, _repeated_file_codec);
                            break;
                        }
                }
            }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the CodeGeneratorResponse message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static partial class Types
        {
            /// <summary>
            ///  Represents a single generated file.
            /// </summary>
            public sealed partial class File : pb::IMessage<File>
            {
                private static readonly pb::MessageParser<File> _parser = new pb::MessageParser<File>(() => new File());
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public static pb::MessageParser<File> Parser { get { return _parser; } }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public static pbr::MessageDescriptor Descriptor
                {
                    get { return global::Google.Protobuf.Compiler.CodeGeneratorResponse.Descriptor.NestedTypes[0]; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                pbr::MessageDescriptor pb::IMessage.Descriptor
                {
                    get { return Descriptor; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public File()
                {
                    OnConstruction();
                }

                partial void OnConstruction();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public File(File other) : this()
                {
                    name_ = other.name_;
                    insertionPoint_ = other.insertionPoint_;
                    content_ = other.content_;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public File Clone()
                {
                    return new File(this);
                }

                /// <summary>Field number for the "name" field.</summary>
                public const int NameFieldNumber = 1;
                private string name_ = "";
                /// <summary>
                ///  The file name, relative to the output directory.  The name must not
                ///  contain "." or ".." components and must be relative, not be absolute (so,
                ///  the file cannot lie outside the output directory).  "/" must be used as
                ///  the path separator, not "\".
                ///
                ///  If the name is omitted, the content will be appended to the previous
                ///  file.  This allows the generator to break large files into small chunks,
                ///  and allows the generated text to be streamed back to protoc so that large
                ///  files need not reside completely in memory at one time.  Note that as of
                ///  this writing protoc does not optimize for this -- it will read the entire
                ///  CodeGeneratorResponse before writing files to disk.
                /// </summary>
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public string Name
                {
                    get { return name_; }
                    set
                    {
                        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                    }
                }

                /// <summary>Field number for the "insertion_point" field.</summary>
                public const int InsertionPointFieldNumber = 2;
                private string insertionPoint_ = "";
                /// <summary>
                ///  If non-empty, indicates that the named file should already exist, and the
                ///  content here is to be inserted into that file at a defined insertion
                ///  point.  This feature allows a code generator to extend the output
                ///  produced by another code generator.  The original generator may provide
                ///  insertion points by placing special annotations in the file that look
                ///  like:
                ///    @@protoc_insertion_point(NAME)
                ///  The annotation can have arbitrary text before and after it on the line,
                ///  which allows it to be placed in a comment.  NAME should be replaced with
                ///  an identifier naming the point -- this is what other generators will use
                ///  as the insertion_point.  Code inserted at this point will be placed
                ///  immediately above the line containing the insertion point (thus multiple
                ///  insertions to the same point will come out in the order they were added).
                ///  The double-@ is intended to make it unlikely that the generated code
                ///  could contain things that look like insertion points by accident.
                ///
                ///  For example, the C++ code generator places the following line in the
                ///  .pb.h files that it generates:
                ///    // @@protoc_insertion_point(namespace_scope)
                ///  This line appears within the scope of the file's package namespace, but
                ///  outside of any particular class.  Another plugin can then specify the
                ///  insertion_point "namespace_scope" to generate additional classes or
                ///  other declarations that should be placed in this scope.
                ///
                ///  Note that if the line containing the insertion point begins with
                ///  whitespace, the same whitespace will be added to every line of the
                ///  inserted text.  This is useful for languages like Python, where
                ///  indentation matters.  In these languages, the insertion point comment
                ///  should be indented the same amount as any inserted code will need to be
                ///  in order to work correctly in that context.
                ///
                ///  The code generator that generates the initial file and the one which
                ///  inserts into it must both run as part of a single invocation of protoc.
                ///  Code generators are executed in the order in which they appear on the
                ///  command line.
                ///
                ///  If |insertion_point| is present, |name| must also be present.
                /// </summary>
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public string InsertionPoint
                {
                    get { return insertionPoint_; }
                    set
                    {
                        insertionPoint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                    }
                }

                /// <summary>Field number for the "content" field.</summary>
                public const int ContentFieldNumber = 15;
                private string content_ = "";
                /// <summary>
                ///  The file contents.
                /// </summary>
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public string Content
                {
                    get { return content_; }
                    set
                    {
                        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                    }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override bool Equals(object other)
                {
                    return Equals(other as File);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public bool Equals(File other)
                {
                    if (ReferenceEquals(other, null))
                    {
                        return false;
                    }
                    if (ReferenceEquals(other, this))
                    {
                        return true;
                    }
                    if (Name != other.Name) return false;
                    if (InsertionPoint != other.InsertionPoint) return false;
                    if (Content != other.Content) return false;
                    return true;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override int GetHashCode()
                {
                    int hash = 1;
                    if (Name.Length != 0) hash ^= Name.GetHashCode();
                    if (InsertionPoint.Length != 0) hash ^= InsertionPoint.GetHashCode();
                    if (Content.Length != 0) hash ^= Content.GetHashCode();
                    return hash;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override string ToString()
                {
                    return pb::JsonFormatter.ToDiagnosticString(this);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void WriteTo(pb::CodedOutputStream output)
                {
                    if (Name.Length != 0)
                    {
                        output.WriteRawTag(10);
                        output.WriteString(Name);
                    }
                    if (InsertionPoint.Length != 0)
                    {
                        output.WriteRawTag(18);
                        output.WriteString(InsertionPoint);
                    }
                    if (Content.Length != 0)
                    {
                        output.WriteRawTag(122);
                        output.WriteString(Content);
                    }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public int CalculateSize()
                {
                    int size = 0;
                    if (Name.Length != 0)
                    {
                        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
                    }
                    if (InsertionPoint.Length != 0)
                    {
                        size += 1 + pb::CodedOutputStream.ComputeStringSize(InsertionPoint);
                    }
                    if (Content.Length != 0)
                    {
                        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
                    }
                    return size;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void MergeFrom(File other)
                {
                    if (other == null)
                    {
                        return;
                    }
                    if (other.Name.Length != 0)
                    {
                        Name = other.Name;
                    }
                    if (other.InsertionPoint.Length != 0)
                    {
                        InsertionPoint = other.InsertionPoint;
                    }
                    if (other.Content.Length != 0)
                    {
                        Content = other.Content;
                    }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void MergeFrom(pb::CodedInputStream input)
                {
                    uint tag;
                    while ((tag = input.ReadTag()) != 0)
                    {
                        switch (tag)
                        {
                            default:
                                input.SkipLastField();
                                break;
                            case 10:
                                {
                                    Name = input.ReadString();
                                    break;
                                }
                            case 18:
                                {
                                    InsertionPoint = input.ReadString();
                                    break;
                                }
                            case 122:
                                {
                                    Content = input.ReadString();
                                    break;
                                }
                        }
                    }
                }

            }

        }
        #endregion

    }

    #endregion

}

#endregion Designer generated code
