// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: math.proto

#region Designer generated code

using DotBPE.Protocol.Amp;
using DotBPE.Rpc;
using Google.Protobuf;
using System.Threading.Tasks;

namespace MathCommon
{
    //start for class AbstractMathInner
    public abstract class MathInnerBase : ServiceActor
    {
        protected override int ServiceId => 10006;


        public override Task<AmpMessage> ProcessAsync(AmpMessage req)
        {
            switch (req.MessageId)
            {

                //方法 MathInner.Plus
                case 1: return this.ProcessPlusAsync(req);

                default: return base.ProcessNotFoundAsync(req);
            }
        }



        //调用委托
        private async Task<AmpMessage> ProcessPlusAsync(AmpMessage req)
        {
            AddReq request = null;

            if (req.Data == null)
            {
                request = new AddReq();
            }
            else
            {
                request = AddReq.Parser.ParseFrom(req.Data);
            }

            req.FriendlyServiceName = "MathInner.Plus";

            var result = await PlusAsync(request);
            var response = AmpMessage.CreateResponseMessage(req.ServiceId, req.MessageId);

            response.FriendlyServiceName = "MathInner.Plus";
            response.Code = result.Code;
            if (result.Data != null)
            {
                response.Data = result.Data.ToByteArray();
            }
            return response;
        }
        //抽象方法
        public abstract Task<RpcResult<AddRes>> PlusAsync( AddReq req);

    }

    //end for class AbstractMathInner
}

#endregion Designer generated code