// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/inner/apaper_inner.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Survey.Core {

  /// <summary>Holder for reflection information generated from service/inner/apaper_inner.proto</summary>
  public static partial class ApaperInnerReflection {

    #region Descriptor
    /// <summary>File descriptor for service/inner/apaper_inner.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ApaperInnerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBzZXJ2aWNlL2lubmVyL2FwYXBlcl9pbm5lci5wcm90bxIGZG90YnBlGhNk",
            "b3RicGVfb3B0aW9uLnByb3RvGhRtZXNzYWdlL2FwYXBlci5wcm90bzLiAQoS",
            "QVBhcGVySW5uZXJTZXJ2aWNlEkAKClNhdmVBUGFwZXISFS5kb3RicGUuU2F2",
            "ZUFQYXBlclJlcRoVLmRvdGJwZS5TYXZlQVBhcGVyUnNwIgTQ8xgBEkYKD1F1",
            "ZXJ5QVBhcGVyTGlzdBIWLmRvdGJwZS5RdWVyeUFQYXBlclJlcRoVLmRvdGJw",
            "ZS5BUGFwZXJMaXN0UnNwIgTQ8xgCEjoKCUdldEFQYXBlchIULmRvdGJwZS5H",
            "ZXRBUGFwZXJSZXEaES5kb3RicGUuQVBhcGVyUnNwIgTQ8xgDGgbI8xiinAFC",
            "FEgBqgILU3VydmV5LkNvcmXw8xgBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotBPE.Protobuf.DotbpeOptionReflection.Descriptor, global::Survey.Core.ApaperReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
