// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufObjectfactory
#region Designer generated code

using System; 
using System.Collections.Generic; 
using System.Text; 
using Google.Protobuf; 
using Google.Protobuf.Reflection; 

namespace Survey.Core {
public class ProtobufObjectFactory {
public static IMessage GetRequestTemplate(int serviceId,int messageId)
{
if(serviceId == 10000 && messageId == 1){ return new SaveAPaperReq() ;
}
if(serviceId == 10000 && messageId == 2){ return new QueryAPaperReq() ;
}
if(serviceId == 10000 && messageId == 3){ return new GetAPaperReq() ;
}

if(serviceId == 20002 && messageId == 1){ return new SaveAPaperReq() ;
}
if(serviceId == 20002 && messageId == 2){ return new QueryAPaperReq() ;
}
if(serviceId == 20002 && messageId == 3){ return new GetAPaperReq() ;
}

if(serviceId == 20001 && messageId == 1){ return new SaveQPaperReq() ;
}
if(serviceId == 20001 && messageId == 2){ return new QueryQPaperReq() ;
}
if(serviceId == 20001 && messageId == 3){ return new GetQPaperReq() ;
}

return null;
}
public static IMessage GetResponseTemplate(int serviceId,int messageId)
{
if(serviceId == 10000 && messageId == 1){ return new SaveAPaperRsp() ;
}
if(serviceId == 10000 && messageId == 2){ return new APaperListRsp() ;
}
if(serviceId == 10000 && messageId == 3){ return new APaperRsp() ;
}

if(serviceId == 20002 && messageId == 1){ return new SaveAPaperRsp() ;
}
if(serviceId == 20002 && messageId == 2){ return new APaperListRsp() ;
}
if(serviceId == 20002 && messageId == 3){ return new APaperRsp() ;
}

if(serviceId == 20001 && messageId == 1){ return new SaveQPaperRsp() ;
}
if(serviceId == 20001 && messageId == 2){ return new QPaperListRsp() ;
}
if(serviceId == 20001 && messageId == 3){ return new QPaperRsp() ;
}

return null;
}
}
}
#endregion
