// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/inner/qpaper_inner.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Survey.Core {

  /// <summary>Holder for reflection information generated from service/inner/qpaper_inner.proto</summary>
  public static partial class QpaperInnerReflection {

    #region Descriptor
    /// <summary>File descriptor for service/inner/qpaper_inner.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QpaperInnerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBzZXJ2aWNlL2lubmVyL3FwYXBlcl9pbm5lci5wcm90bxIGZG90YnBlGhNk",
            "b3RicGVfb3B0aW9uLnByb3RvGhRtZXNzYWdlL3FwYXBlci5wcm90bzLiAQoS",
            "UVBhcGVySW5uZXJTZXJ2aWNlEkAKClNhdmVRUGFwZXISFS5kb3RicGUuU2F2",
            "ZVFQYXBlclJlcRoVLmRvdGJwZS5TYXZlUVBhcGVyUnNwIgTQ8xgBEkYKD1F1",
            "ZXJ5UVBhcGVyTGlzdBIWLmRvdGJwZS5RdWVyeVFQYXBlclJlcRoVLmRvdGJw",
            "ZS5RUGFwZXJMaXN0UnNwIgTQ8xgCEjoKCUdldFFQYXBlchIULmRvdGJwZS5H",
            "ZXRRUGFwZXJSZXEaES5kb3RicGUuUVBhcGVyUnNwIgTQ8xgDGgbI8xihnAFC",
            "FEgBqgILU3VydmV5LkNvcmXw8xgBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotBPE.Protobuf.DotbpeOptionReflection.Descriptor, global::Survey.Core.QpaperReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
