// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/inner/qpaper_inner_20001.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Survey.Core {

  /// <summary>Holder for reflection information generated from service/inner/qpaper_inner_20001.proto</summary>
  public static partial class QpaperInner20001Reflection {

    #region Descriptor
    /// <summary>File descriptor for service/inner/qpaper_inner_20001.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QpaperInner20001Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZzZXJ2aWNlL2lubmVyL3FwYXBlcl9pbm5lcl8yMDAwMS5wcm90bxIGZG90",
            "YnBlGhNkb3RicGVfb3B0aW9uLnByb3RvGhRtZXNzYWdlL3FwYXBlci5wcm90",
            "bzLlAgoSUVBhcGVySW5uZXJTZXJ2aWNlEkAKClNhdmVRUGFwZXISFS5kb3Ri",
            "cGUuU2F2ZVFQYXBlclJlcRoVLmRvdGJwZS5TYXZlUVBhcGVyUnNwIgTQ8xgB",
            "EkYKD1F1ZXJ5UVBhcGVyTGlzdBIWLmRvdGJwZS5RdWVyeVFQYXBlclJlcRoV",
            "LmRvdGJwZS5RUGFwZXJMaXN0UnNwIgTQ8xgCEjoKCUdldFFQYXBlchIULmRv",
            "dGJwZS5HZXRRUGFwZXJSZXEaES5kb3RicGUuUVBhcGVyUnNwIgTQ8xgDEkIK",
            "DUdldFFQYXBlckZ1bGwSFC5kb3RicGUuR2V0UVBhcGVyUmVxGhUuZG90YnBl",
            "LlFQYXBlckZ1bGxSc3AiBNDzGAQSPQoOQWRkQVBhcGVyQ291bnQSFC5kb3Ri",
            "cGUuQWRkQVBhcGVyUmVxGg8uZG90YnBlLlZvaWRSc3AiBNDzGAUaBsjzGKGc",
            "AUIQSAGqAgtTdXJ2ZXkuQ29yZVAAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotBPE.Protobuf.DotbpeOptionReflection.Descriptor, global::Survey.Core.QpaperReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
