// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/gate/survey_gate_10000.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Survey.Core {

  /// <summary>Holder for reflection information generated from service/gate/survey_gate_10000.proto</summary>
  public static partial class SurveyGate10000Reflection {

    #region Descriptor
    /// <summary>File descriptor for service/gate/survey_gate_10000.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SurveyGate10000Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRzZXJ2aWNlL2dhdGUvc3VydmV5X2dhdGVfMTAwMDAucHJvdG8SBmRvdGJw",
            "ZRoTZG90YnBlX29wdGlvbi5wcm90bxoUbWVzc2FnZS9hcGFwZXIucHJvdG8a",
            "FG1lc3NhZ2UvcXBhcGVyLnByb3RvMrwFChFTdXJ2ZXlHYXRlU2VydmljZRJw",
            "CgpTYXZlUVBhcGVyEhUuZG90YnBlLlNhdmVRUGFwZXJSZXEaFS5kb3RicGUu",
            "U2F2ZVFQYXBlclJzcCI00PMYC9rzGCwKEC9hcGkvcXBhcGVyL3NhdmUSBHBv",
            "c3QaEuS/neWtmOmXruWNt+S/oeaBrxJwCg9RdWVyeVFQYXBlckxpc3QSFi5k",
            "b3RicGUuUXVlcnlRUGFwZXJSZXEaFS5kb3RicGUuUVBhcGVyTGlzdFJzcCIu",
            "0PMYDNrzGCYKES9hcGkvcXBhcGVyL3F1ZXJ5EgNhbGwaDOafpeivouWIl+ih",
            "qBJoCglHZXRRUGFwZXISFC5kb3RicGUuR2V0UVBhcGVyUmVxGhEuZG90YnBl",
            "LlFQYXBlclJzcCIy0PMYDdrzGCoKDy9hcGkvcXBhcGVyL2dldBIDZ2V0GhLo",
            "jrflj5bpl67ljbfkv6Hmga8ScAoKU2F2ZUFQYXBlchIVLmRvdGJwZS5TYXZl",
            "QVBhcGVyUmVxGhUuZG90YnBlLlNhdmVBUGFwZXJSc3AiNNDzGBXa8xgsChAv",
            "YXBpL2FwYXBlci9zYXZlEgRwb3N0GhLkv53lrZjnrZTljbfkv6Hmga8SdgoP",
            "UXVlcnlBUGFwZXJMaXN0EhYuZG90YnBlLlF1ZXJ5QVBhcGVyUmVxGhUuZG90",
            "YnBlLkFQYXBlckxpc3RSc3AiNNDzGBba8xgsChEvYXBpL2FwYXBlci9xdWVy",
            "eRIDYWxsGhLmn6Xor6LnrZTljbfkv6Hmga8SaAoJR2V0QVBhcGVyEhQuZG90",
            "YnBlLkdldEFQYXBlclJlcRoRLmRvdGJwZS5BUGFwZXJSc3AiMtDzGBfa8xgq",
            "Cg8vYXBpL2FwYXBlci9nZXQSA2dldBoS6I635Y+W562U5Y235L+h5oGvGgXI",
            "8xiQTkIYSAGqAgtTdXJ2ZXkuQ29yZfDzGAH48xgBUABiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotBPE.Protobuf.DotbpeOptionReflection.Descriptor, global::Survey.Core.ApaperReflection.Descriptor, global::Survey.Core.QpaperReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
