// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/inner/user_inner_20003.proto
#region Designer generated code

using System; 
using System.Threading.Tasks; 
using DotBPE.Rpc; 
using DotBPE.Protocol.Amp; 
using DotBPE.Rpc.Exceptions; 
using Google.Protobuf; 

namespace Survey.Core {

//start for class UserInnerServiceClient
   public sealed class UserInnerServiceClient : AmpInvokeClient 
    {
        public UserInnerServiceClient(IRpcClient<AmpMessage> client) : base(client)
        {
        }
        public UserInnerServiceClient(string remoteAddress) : base(remoteAddress)
        {
        }
        public async Task<RpcResult<RegisterRsp>> RegisterAsync(RegisterReq request,int timeOut=3000)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(20003, 1);
            message.Data = request.ToByteArray();
            var response = await base.CallInvoker.AsyncCall(message,timeOut);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
            var result = new RpcResult<RegisterRsp>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            else if (response.Data == null)
            {
                result.Code = ErrorCodes.CODE_INTERNAL_ERROR;
            }
            else
            {
                result.Data = RegisterRsp.Parser.ParseFrom(response.Data);
            }
            return result;
        }

        //同步方法
        public RpcResult<RegisterRsp> Register(RegisterReq request)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(20003, 1);
            message.Data = request.ToByteArray();
            var response =  base.CallInvoker.BlockingCall(message);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
            var result = new RpcResult<RegisterRsp>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            else if (response.Data == null)
            {
                result.Code = ErrorCodes.CODE_INTERNAL_ERROR;
            }
            else
            {
                result.Data = RegisterRsp.Parser.ParseFrom(response.Data);
            }
            return result;
         }
        public async Task<RpcResult<LoginRsp>> LoginAsync(LoginReq request,int timeOut=3000)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(20003, 2);
            message.Data = request.ToByteArray();
            var response = await base.CallInvoker.AsyncCall(message,timeOut);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
            var result = new RpcResult<LoginRsp>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            else if (response.Data == null)
            {
                result.Code = ErrorCodes.CODE_INTERNAL_ERROR;
            }
            else
            {
                result.Data = LoginRsp.Parser.ParseFrom(response.Data);
            }
            return result;
        }

        //同步方法
        public RpcResult<LoginRsp> Login(LoginReq request)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(20003, 2);
            message.Data = request.ToByteArray();
            var response =  base.CallInvoker.BlockingCall(message);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
            var result = new RpcResult<LoginRsp>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            else if (response.Data == null)
            {
                result.Code = ErrorCodes.CODE_INTERNAL_ERROR;
            }
            else
            {
                result.Data = LoginRsp.Parser.ParseFrom(response.Data);
            }
            return result;
         }
        public async Task<RpcResult<EditUserRsp>> EditAsync(EditUserReq request,int timeOut=3000)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(20003, 3);
            message.Data = request.ToByteArray();
            var response = await base.CallInvoker.AsyncCall(message,timeOut);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
            var result = new RpcResult<EditUserRsp>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            else if (response.Data == null)
            {
                result.Code = ErrorCodes.CODE_INTERNAL_ERROR;
            }
            else
            {
                result.Data = EditUserRsp.Parser.ParseFrom(response.Data);
            }
            return result;
        }

        //同步方法
        public RpcResult<EditUserRsp> Edit(EditUserReq request)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(20003, 3);
            message.Data = request.ToByteArray();
            var response =  base.CallInvoker.BlockingCall(message);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
            var result = new RpcResult<EditUserRsp>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            else if (response.Data == null)
            {
                result.Code = ErrorCodes.CODE_INTERNAL_ERROR;
            }
            else
            {
                result.Data = EditUserRsp.Parser.ParseFrom(response.Data);
            }
            return result;
         }
        public async Task<RpcResult<GetUserRsp>> GetUserInfoAsync(GetUserReq request,int timeOut=3000)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(20003, 4);
            message.Data = request.ToByteArray();
            var response = await base.CallInvoker.AsyncCall(message,timeOut);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
            var result = new RpcResult<GetUserRsp>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            else if (response.Data == null)
            {
                result.Code = ErrorCodes.CODE_INTERNAL_ERROR;
            }
            else
            {
                result.Data = GetUserRsp.Parser.ParseFrom(response.Data);
            }
            return result;
        }

        //同步方法
        public RpcResult<GetUserRsp> GetUserInfo(GetUserReq request)
        {
            AmpMessage message = AmpMessage.CreateRequestMessage(20003, 4);
            message.Data = request.ToByteArray();
            var response =  base.CallInvoker.BlockingCall(message);
            if (response == null)
            {
                throw new RpcException("error,response is null !");
            }
            var result = new RpcResult<GetUserRsp>();
            if (response.Code != 0)
            {
                result.Code = response.Code;
            }
            else if (response.Data == null)
            {
                result.Code = ErrorCodes.CODE_INTERNAL_ERROR;
            }
            else
            {
                result.Data = GetUserRsp.Parser.ParseFrom(response.Data);
            }
            return result;
         }
     }
//end for class UserInnerServiceClient
}
#endregion
