// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/gate/user_gate_10001.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Survey.Core {

  /// <summary>Holder for reflection information generated from service/gate/user_gate_10001.proto</summary>
  public static partial class UserGate10001Reflection {

    #region Descriptor
    /// <summary>File descriptor for service/gate/user_gate_10001.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserGate10001Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJzZXJ2aWNlL2dhdGUvdXNlcl9nYXRlXzEwMDAxLnByb3RvEgZkb3RicGUa",
            "E2RvdGJwZV9vcHRpb24ucHJvdG8aEm1lc3NhZ2UvdXNlci5wcm90bzLPAgoP",
            "VXNlckdhdGVTZXJ2aWNlEmYKCFJlZ2lzdGVyEhMuZG90YnBlLlJlZ2lzdGVy",
            "UmVxGhMuZG90YnBlLlJlZ2lzdGVyUnNwIjDQ8xgf2vMYKAoSL2FwaS91c2Vy",
            "L3JlZ2lzdGVyEgRwb3N0Ggzms6jlhoznlKjmiLcSWgoFTG9naW4SEC5kb3Ri",
            "cGUuTG9naW5SZXEaEC5kb3RicGUuTG9naW5Sc3AiLdDzGCDa8xglCg8vYXBp",
            "L3VzZXIvbG9naW4SBHBvc3QaDOeUqOaIt+eZu+W9lRJxCghFZGl0VXNlchIT",
            "LmRvdGJwZS5FZGl0VXNlclJlcRoTLmRvdGJwZS5FZGl0VXNlclJzcCI70PMY",
            "IdrzGDMKDi9hcGkvdXNlci9zYXZlEgRwb3N0Ghvkv53lrZjkv67mlLnnmoTn",
            "lKjmiLfkv6Hmga8aBcjzGJFOQhhIAaoCC1N1cnZleS5Db3Jl8PMYAfjzGAFQ",
            "AGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotBPE.Protobuf.DotbpeOptionReflection.Descriptor, global::Survey.Core.UserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
