// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/inner/user_inner_20003.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Survey.Core {

  /// <summary>Holder for reflection information generated from service/inner/user_inner_20003.proto</summary>
  public static partial class UserInner20003Reflection {

    #region Descriptor
    /// <summary>File descriptor for service/inner/user_inner_20003.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserInner20003Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRzZXJ2aWNlL2lubmVyL3VzZXJfaW5uZXJfMjAwMDMucHJvdG8SBmRvdGJw",
            "ZRoTZG90YnBlX29wdGlvbi5wcm90bxoSbWVzc2FnZS91c2VyLnByb3RvMv4B",
            "ChBVc2VySW5uZXJTZXJ2aWNlEjoKCFJlZ2lzdGVyEhMuZG90YnBlLlJlZ2lz",
            "dGVyUmVxGhMuZG90YnBlLlJlZ2lzdGVyUnNwIgTQ8xgBEjEKBUxvZ2luEhAu",
            "ZG90YnBlLkxvZ2luUmVxGhAuZG90YnBlLkxvZ2luUnNwIgTQ8xgCEjYKBEVk",
            "aXQSEy5kb3RicGUuRWRpdFVzZXJSZXEaEy5kb3RicGUuRWRpdFVzZXJSc3Ai",
            "BNDzGAMSOwoLR2V0VXNlckluZm8SEi5kb3RicGUuR2V0VXNlclJlcRoSLmRv",
            "dGJwZS5HZXRVc2VyUnNwIgTQ8xgEGgbI8xijnAFCEEgBqgILU3VydmV5LkNv",
            "cmVQAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotBPE.Protobuf.DotbpeOptionReflection.Descriptor, global::Survey.Core.UserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
