// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dotbpe_option.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DotBPE.Protobuf {

  /// <summary>Holder for reflection information generated from dotbpe_option.proto</summary>
  public static partial class DotbpeOptionReflection {

    #region Descriptor
    /// <summary>File descriptor for dotbpe_option.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DotbpeOptionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNkb3RicGVfb3B0aW9uLnByb3RvEgZkb3RicGUaIGdvb2dsZS9wcm90b2J1",
            "Zi9kZXNjcmlwdG9yLnByb3RvImMKDUh0dHBBcGlPcHRpb24SDAoEcGF0aBgB",
            "IAEoCRIOCgZtZXRob2QYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkSDwoH",
            "dGltZW91dBgEIAEoBRIOCgZwbHVnaW4YBSABKAk6NQoKc2VydmljZV9pZBIf",
            "Lmdvb2dsZS5wcm90b2J1Zi5TZXJ2aWNlT3B0aW9ucxi5jgMgASgFOkkKHmRp",
            "c2FibGVfZ2VuZXJpY19zZXJ2aWNlX2NsaWVudBIfLmdvb2dsZS5wcm90b2J1",
            "Zi5TZXJ2aWNlT3B0aW9ucxi7jgMgASgIOkkKHmRpc2FibGVfZ2VuZXJpY19z",
            "ZXJ2aWNlX3NlcnZlchIfLmdvb2dsZS5wcm90b2J1Zi5TZXJ2aWNlT3B0aW9u",
            "cxi8jgMgASgIOjQKCm1lc3NhZ2VfaWQSHi5nb29nbGUucHJvdG9idWYuTWV0",
            "aG9kT3B0aW9ucxi6jgMgASgFOlAKD2h0dHBfYXBpX29wdGlvbhIeLmdvb2ds",
            "ZS5wcm90b2J1Zi5NZXRob2RPcHRpb25zGLuOAyABKAsyFS5kb3RicGUuSHR0",
            "cEFwaU9wdGlvbjpHCh9kaXNhYmxlX2dlbmVyaWNfc2VydmljZXNfY2xpZW50",
            "EhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGLuOAyABKAg6RwofZGlz",
            "YWJsZV9nZW5lcmljX3NlcnZpY2VzX3NlcnZlchIcLmdvb2dsZS5wcm90b2J1",
            "Zi5GaWxlT3B0aW9ucxi8jgMgASgIOjwKFGdlbmVyaWNfbWFya2Rvd25fZG9j",
            "EhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGL2OAyABKAg6PQoVZ2Vu",
            "ZXJpY19vYmplY3RmYWN0b3J5EhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRp",
            "b25zGL6OAyABKAg6PwoXZ2VuZXJpY19odHRwX2FwaV9yb3V0ZXMSHC5nb29n",
            "bGUucHJvdG9idWYuRmlsZU9wdGlvbnMYv44DIAEoCEISqgIPRG90QlBFLlBy",
            "b3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DotBPE.Protobuf.HttpApiOption), global::DotBPE.Protobuf.HttpApiOption.Parser, new[]{ "Path", "Method", "Description", "Timeout", "Plugin" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// </summary>
  public sealed partial class HttpApiOption : pb::IMessage<HttpApiOption> {
    private static readonly pb::MessageParser<HttpApiOption> _parser = new pb::MessageParser<HttpApiOption>(() => new HttpApiOption());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HttpApiOption> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DotBPE.Protobuf.DotbpeOptionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HttpApiOption() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HttpApiOption(HttpApiOption other) : this() {
      path_ = other.path_;
      method_ = other.method_;
      description_ = other.description_;
      timeout_ = other.timeout_;
      plugin_ = other.plugin_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HttpApiOption Clone() {
      return new HttpApiOption(this);
    }

    /// <summary>Field number for the "path" field.</summary>
    public const int PathFieldNumber = 1;
    private string path_ = "";
    /// <summary>
    ///  路径
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Path {
      get { return path_; }
      set {
        path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "method" field.</summary>
    public const int MethodFieldNumber = 2;
    private string method_ = "";
    /// <summary>
    /// 请求的方法
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Method {
      get { return method_; }
      set {
        method_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 3;
    private string description_ = "";
    /// <summary>
    /// 注释说明
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timeout" field.</summary>
    public const int TimeoutFieldNumber = 4;
    private int timeout_;
    /// <summary>
    /// 调用超时配置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Timeout {
      get { return timeout_; }
      set {
        timeout_ = value;
      }
    }

    /// <summary>Field number for the "plugin" field.</summary>
    public const int PluginFieldNumber = 5;
    private string plugin_ = "";
    /// <summary>
    /// 插件
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Plugin {
      get { return plugin_; }
      set {
        plugin_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HttpApiOption);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HttpApiOption other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Path != other.Path) return false;
      if (Method != other.Method) return false;
      if (Description != other.Description) return false;
      if (Timeout != other.Timeout) return false;
      if (Plugin != other.Plugin) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Path.Length != 0) hash ^= Path.GetHashCode();
      if (Method.Length != 0) hash ^= Method.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (Timeout != 0) hash ^= Timeout.GetHashCode();
      if (Plugin.Length != 0) hash ^= Plugin.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Path.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Path);
      }
      if (Method.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Method);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Description);
      }
      if (Timeout != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Timeout);
      }
      if (Plugin.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Plugin);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
      }
      if (Method.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Method);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (Timeout != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Timeout);
      }
      if (Plugin.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Plugin);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HttpApiOption other) {
      if (other == null) {
        return;
      }
      if (other.Path.Length != 0) {
        Path = other.Path;
      }
      if (other.Method.Length != 0) {
        Method = other.Method;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.Timeout != 0) {
        Timeout = other.Timeout;
      }
      if (other.Plugin.Length != 0) {
        Plugin = other.Plugin;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Path = input.ReadString();
            break;
          }
          case 18: {
            Method = input.ReadString();
            break;
          }
          case 26: {
            Description = input.ReadString();
            break;
          }
          case 32: {
            Timeout = input.ReadInt32();
            break;
          }
          case 42: {
            Plugin = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
